events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /users/ {
            proxy_pass http://users_api:8000;
        }
        location /login {
            proxy_pass http://users_api:8000;
        }

        location /orders/ {
            proxy_pass http://orders_api:8000;
        }

        location /products/ {
            proxy_pass http://inventory_api:8000;
        }
    }
}